import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    art_text: {
        color: '#E7E4E7',
        fontSize: 16,
        fontWeight: 'bold',
        // position: 'absolute',
        // bottom: 0,
        // right: 0,
        // paddingBottom: 10,
        // paddingRight: 10,
        // paddingLeft: 10,
        shadowColor: "rgba(0, 0, 0, 0.25)",
        shadowOffset: { width: 2, height: 2 },
        shadowRadius: 2,
        shadowOpacity: 1,
        elevation: 5,
        textAlign: 'center',
    },
    banner_title: {
        color: '#E7E4E7',
        fontSize: 26,
        fontWeight: 'bold',
        position:'absolute',
        bottom:100,
        left:20,
        shadowColor: "rgba(0, 0, 0, 0.25)",
        shadowOffset: { width: 2, height: 2 },
        shadowRadius: 2,
        shadowOpacity: 1,
        elevation: 5,
    },
    banner_text: {
        color: '#E7E4E7',
        fontSize: 18,
        fontWeight: 'bold',
        position:'absolute',
        bottom:80,
        left:20,
        shadowColor: "rgba(0, 0, 0, 0.25)",
        shadowOffset: { width: 2, height: 2 },
        shadowRadius: 2,
        shadowOpacity: 1,
        elevation: 5,
    },
    detail_name: {
        color: '#E7E4E7',
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    detail_author: {
        color: '#E7E4E7',
        fontSize: 18,
        fontWeight: '500',
    },
    detail_Intro: {
        color: '#E7E4E7',
        fontSize: 16,
        fontWeight: '400',
        marginRight:20,
        marginLeft:20,
        marginBottom:10,
        marginTop:10,
        lineHeight:22,
    },
    detailText_title: {
        color: '#B8860B',
        fontSize: 18,
        fontWeight: 'bold',
        marginTop:4
    },
    detailText_text: {
        color: '#E7E4E7',
        fontSize: 16,
        fontWeight: '500',
    },
    detailText_btn: {
        color: '#E7E4E7',
        fontSize: 20,
        fontWeight: 'bold',
    },
    detail_back_text: {
        color: '#E7E4E7',
        fontSize: 20,
        fontWeight: 'bold',
    }
})